/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'bookmarked' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text, Subject, IDL.Text, IDL.Vec(IDL.Text)],
      [Note],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'filterBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBookmarkedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
  'getRecentlyAccessedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getSubjectCount' : IDL.Func([Subject], [IDL.Nat], ['query']),
  'getTotalNoteCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'toggleBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Subject, IDL.Text, IDL.Vec(IDL.Text)],
      [Note],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'maths' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'bookmarked' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, Subject, IDL.Text, IDL.Vec(IDL.Text)],
        [Note],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'filterBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBookmarkedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
    'getRecentlyAccessedNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getSubjectCount' : IDL.Func([Subject], [IDL.Nat], ['query']),
    'getTotalNoteCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'toggleBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Subject, IDL.Text, IDL.Vec(IDL.Text)],
        [Note],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };