/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'id' : bigint,
  'title' : string,
  'topic' : string,
  'content' : string,
  'subject' : Subject,
  'createdAt' : Time,
  'tags' : Array<string>,
  'updatedAt' : Time,
  'bookmarked' : boolean,
}
export type Subject = { 'maths' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<
    [string, string, Subject, string, Array<string>],
    Note
  >,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'filterBySubject' : ActorMethod<[Subject], Array<Note>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getBookmarkedNotes' : ActorMethod<[], Array<Note>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[bigint], Note>,
  'getRecentlyAccessedNotes' : ActorMethod<[], Array<Note>>,
  'getSubjectCount' : ActorMethod<[Subject], bigint>,
  'getTotalNoteCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'toggleBookmark' : ActorMethod<[bigint], boolean>,
  'updateNote' : ActorMethod<
    [bigint, string, string, Subject, string, Array<string>],
    Note
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];